// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgfY77mRO-hdIwZJrl5K7dKRSuEHY2R0E',
    appId: '1:817792816547:web:4af85888f3d5c6fb16f616',
    messagingSenderId: '817792816547',
    projectId: 'assignment-b37de',
    authDomain: 'assignment-b37de.firebaseapp.com',
    storageBucket: 'assignment-b37de.appspot.com',
    measurementId: 'G-HNGGPV7PXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs-BgxYfdonLHMU4H5sr5rCw-ky9rhlro',
    appId: '1:817792816547:android:65b711bc88f82bb816f616',
    messagingSenderId: '817792816547',
    projectId: 'assignment-b37de',
    storageBucket: 'assignment-b37de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHsiYVmeiIT478Ov67wa-d16T3iFlGCy8',
    appId: '1:817792816547:ios:84424bcd56edf96e16f616',
    messagingSenderId: '817792816547',
    projectId: 'assignment-b37de',
    storageBucket: 'assignment-b37de.appspot.com',
    iosBundleId: 'com.example.flutterAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHsiYVmeiIT478Ov67wa-d16T3iFlGCy8',
    appId: '1:817792816547:ios:84424bcd56edf96e16f616',
    messagingSenderId: '817792816547',
    projectId: 'assignment-b37de',
    storageBucket: 'assignment-b37de.appspot.com',
    iosBundleId: 'com.example.flutterAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgfY77mRO-hdIwZJrl5K7dKRSuEHY2R0E',
    appId: '1:817792816547:web:fb8aa6aa80fd1bd416f616',
    messagingSenderId: '817792816547',
    projectId: 'assignment-b37de',
    authDomain: 'assignment-b37de.firebaseapp.com',
    storageBucket: 'assignment-b37de.appspot.com',
    measurementId: 'G-MPS7LQVSYL',
  );
}
