// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN662QI2VbVfplDKmExwspG48yGxgD3Ek',
    appId: '1:237338423708:web:5f091cd39264731e119859',
    messagingSenderId: '237338423708',
    projectId: 'basiciapp',
    authDomain: 'basiciapp.firebaseapp.com',
    databaseURL: 'https://basiciapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'basiciapp.appspot.com',
    measurementId: 'G-DXD7069W5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARRzjmyhvnQVbpjwlzjzKaKXyzIWk56zA',
    appId: '1:237338423708:android:05cb1d278049e87c119859',
    messagingSenderId: '237338423708',
    projectId: 'basiciapp',
    databaseURL: 'https://basiciapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'basiciapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt7GuSstQzU27evgDZ3HYV73zYdrdGj4c',
    appId: '1:237338423708:ios:5b790d3468a6994a119859',
    messagingSenderId: '237338423708',
    projectId: 'basiciapp',
    databaseURL: 'https://basiciapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'basiciapp.appspot.com',
    iosBundleId: 'com.example.pawfect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt7GuSstQzU27evgDZ3HYV73zYdrdGj4c',
    appId: '1:237338423708:ios:5b790d3468a6994a119859',
    messagingSenderId: '237338423708',
    projectId: 'basiciapp',
    databaseURL: 'https://basiciapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'basiciapp.appspot.com',
    iosBundleId: 'com.example.pawfect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN662QI2VbVfplDKmExwspG48yGxgD3Ek',
    appId: '1:237338423708:web:4897c4c31d82c4ee119859',
    messagingSenderId: '237338423708',
    projectId: 'basiciapp',
    authDomain: 'basiciapp.firebaseapp.com',
    databaseURL: 'https://basiciapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'basiciapp.appspot.com',
    measurementId: 'G-T3G2MDR4F0',
  );
}
